=== vlsi/ksar/src/main/resources/Config.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Config.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE ConfiG SYSTEM "Config.dtd">

    <ConfiG>
    ...
    </ConfiG>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ConfiG (OS|colors)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT colors (itemcolor)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT itemcolor (color)*>
<!ATTLIST itemcolor
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT color (#PCDATA)>


<!ELEMENT History (cnx)*>
<!ATTLIST itemcolor
    link CDATA #IMPLIED
    type CDATA #IMPLIED
  >

<!ELEMENT cnx (command)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OS (OSType)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OSType (Graph|Stat)*>
<!ATTLIST OSType
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Stat (graphname|headerstr)*>
<!ATTLIST Stat
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT headerstr (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT graphname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Graph (Plot|Stack)*>
<!ATTLIST Graph
    type CDATA #IMPLIED
    Title CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Stack (range|cols|format)*>
<!ATTLIST Stack
    size CDATA #IMPLIED
    Title CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cols (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT range (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT format EMPTY>
<!ATTLIST format
   base CDATA #IMPLIED
   factor CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Plot (range|cols|format)*>
<!ATTLIST Plot
    size CDATA #IMPLIED
    Title CDATA #IMPLIED
  >

=== vlsi/ksar/src/main/resources/Esar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ConfiG PUBLIC "-//NET/ATOMIQUE/KSAR/CONFIG.DTD" "Config.dtd">
<!--
    Document   : Config.xml
    Created on : 10 aoÃ»t 2010, 16:31
    Author     : Max
    Description:
        Configure color of graphs

-->


<ConfiG>

    <!--  BEGIN OS -->
    <OS>
        <OSType name="Esar">
            <Stat name="file">
                <headerstr>CPU iget/s namei/s dirbk/s</headerstr>
                <graphname>FILE</graphname>
            </Stat>
            <Stat name="buffer">
                <headerstr>CPU bread/s lread/s %rcache bwrite/s lwrite/s %wcache phread/s phwrite/s</headerstr>
                <graphname>BUFFER</graphname>
            </Stat>
            <Stat name="syscall">
                <headerstr>CPU scall/s sread/s swrit/s fork/s vfork/s exec/s rchar/s wchar/s intr/s trap/s</headerstr>
                <graphname>SYSCALL</graphname>
            </Stat>
            <Stat name="device">
                <headerstr>device %busy read/s write/s kbr/s kbw/s avqr avqw avwait avserv</headerstr>
                <graphname>DEVICE</graphname>
            </Stat>
            <Stat name="">
                <headerstr>CPU pgout/s ppgout/s pgfree/s pgscan/s %ufs_ipf</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>CPU msg/s sema/s</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>CPU atch/s pgin/s ppgin/s pflt/s vflt/s slock/s</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>runq-sz %runocc swpq-sz %swpocc</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>freemem freeswap swpunalloc swpreserv swpalloc</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>CPU %usr %sys %wio %idle %w_io %w_swap %w_pio</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>CPU swpin/s kbswin/s swpot/s kbswot/s pswch/s</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>CPU rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>la1 la5 la15 nproc</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>interface ipacket/s opacket/s ibits/s obits/s ierror/s oerror/s %util</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>interface bcstrcv/s bcstxmt/s mcstrcv/s mcstxmt/s norcvbf/s noxmtbf/s coll/s</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>pset la1 la5 la15 ncpus</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>RAWIP inDgms/s inErrs/s outDgms/s outErrs/s CksErrs/s</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>UDP inDgms/s inErrs/s outDgms/s outErrs/s</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>TCP actvOpens/s atmptFails/s currEstab estabRsts/s hlfOpenDrp/s listenDrop/s listDropQ0/s passvOpens/s</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>RPCD(tcp) badcalls badlen calls dupchk dupreqs nullrcv xdrcall</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>RPC(tcp) badcalls badverfs badxids calls cantconn intrpts newcreds nomem timeouts timers</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>RPCD(udp) badcalls badlen calls dupchk dupreqs nullrcv xdrcall</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>RPC(udp) badcalls badverfs badxids calls cantsend retrans newcreds nomem timeouts timers</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFS v2 create link lookup mkdir read readdir readlnk remove rename rmdir symlnk write</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFS v2  getattr null root setattr statfs wrcache</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFSD v2 create link lookup mkdir read readdir readlnk remove rename rmdir symlnk write</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFSD v2 getattr null root setattr statfs wrcache</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFS v3 access commit create link lookup mkdir read readlnk remove rename rmdir symlink write</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFS v3 fsstat getattr fsinfo null pathconf setattr mknod readdir readirp</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFSD v3 access commit create link lookup mkdir read readlnk remove rename rmdir symlink write</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr> NFSD v3 fsstat getattr fsinfo null pathconf setattr mknod readdir readirp</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFS v4 access close create link open read readdir readlnk remove rename renew verify write</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFS v4 commit compnd dpurge dreturn getattr lookup lookupp null nverify opencnf opendwg openatr reservd secinfo setattr</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFS v4 lock lockt locku getfh putfh ptpubfh ptrtfh rstrfh savefh setid setidcnf</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFSD v4 access close create link open read readdir readlnk remove rename renew verify write</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFSD v4 commit compnd dpurge dreturn getattr lookup lookupp null nverify opencnf opendwg openatr reservd secinfo setattr</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>NFSD v4 lock lockt locku getfh putfh ptpubfh ptrtfh rstrfh savefh setid setidcnf rlckownr illegal</headerstr>
                <graphname></graphname>
            </Stat>
            <Stat name="">
                <headerstr>Total Kernel Locked Avail</headerstr>
                <graphname></graphname>
            </Stat>
        </OSType>
    </OS>
</ConfiG>

=== vlsi/ksar/src/main/resources/AIX.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ConfiG PUBLIC "-//NET/ATOMIQUE/KSAR/CONFIG.DTD" "config.dtd" >
<!--
    Description:
        Configure statistics and their corresponding graphs (plots+stacks)
-->

<ConfiG>
   
    <!--  BEGIN OS -->
    <OS>
        <OSType name="AIX">
            <Stat name="cswch">
                <headerstr>cswch/s</headerstr>
                <graphname>CSWCH</graphname>
            </Stat>
            <Stat name="file">
                <headerstr>iget/s lookuppn/s dirblk/s</headerstr>
                <graphname>FILE</graphname>
            </Stat>
            <Stat name="syscall">
                <headerstr>scall/s sread/s swrit/s fork/s exec/s rchar/s wchar/s</headerstr>
                <graphname>SYSCALL</graphname>
            </Stat>
            <Stat name="buffer">
                <headerstr>bread/s lread/s %rcache bwrit/s lwrit/s %wcache pread/s pwrit/s</headerstr>
                <graphname>BUFFER</graphname>
            </Stat>
            <Stat name="device1">
                <headerstr>device %busy avque r+w/s blks/s avwait avserv</headerstr>
                <graphname>DEVICE</graphname>
            </Stat>
            <Stat name="device2">
                <headerstr>device %busy avque r+w/s Kbs/s avwait avserv</headerstr>
                <graphname>DEVICE</graphname>
            </Stat>
            <Stat name="msgs">
                <headerstr>msg/s sema/s</headerstr>
                <graphname>MSGS</graphname>
            </Stat>
            <Stat name="kernel">
                <headerstr>ksched/s kproc-ov kexit/s</headerstr>
                <graphname>IGNORE</graphname>
            </Stat>
            <Stat name="runq">
                <headerstr>runq-sz %runocc swpq-sz %swpocc</headerstr>
                <graphname>IGNORE</graphname>
            </Stat>
            <Stat name="slot">
                <headerstr>slots cycle/s fault/s odio/s</headerstr>
                <graphname>SLOT</graphname>
            </Stat>
            <Stat name="proc">
                <headerstr>proc-sz inod-sz file-sz thrd-sz</headerstr>
                <graphname>IGNORE</graphname>
            </Stat>
            <Stat name="tty">
                <headerstr>rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s</headerstr>
                <graphname>TTY</graphname>
            </Stat>
            <Stat name="cpu1">
                <headerstr>%usr %sys %wio %idle</headerstr>
                <graphname>CPU</graphname>
            </Stat>
            <Stat name="cpu2">
                <headerstr>%usr %sys %wio %idle physc</headerstr>
                <graphname>CPU</graphname>
            </Stat>
            <Stat name="cpu3">
                <headerstr>cpu %usr %sys %wio %idle physc</headerstr>
                <graphname>CPUS</graphname>
            </Stat>
            <Stat name="cpu4">
                <headerstr>%usr %sys %wio %idle physc %entc</headerstr>
                <graphname>CPU</graphname>
            </Stat>
            <Graph name="CPU" Title="CPU" type="unique">
                <Stack Title="Used" size="3">
                    <cols>%usr %sys %wio</cols>
                </Stack>
                <Plot Title="Idle">
                    <cols>%idle</cols>
                </Plot>
            </Graph>
            <Graph name="CPUS" Title="CPU" type="multiple">
                <Stack Title="Used" size="3">
                    <cols>%usr %sys %wio</cols>
                </Stack>
                <Plot Title="Idle">
                    <cols>%idle</cols>
                </Plot>
            </Graph>
            <Graph name="TTY" Title="Tty" type="unique">
                <Plot Title="TTY">
                    <cols>rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s</cols>
                </Plot>
            </Graph>
            <Graph name="CSWCH" Title="Context" type="unique">
                <Plot Title="Context">
                    <cols>cswch/s</cols>
                </Plot>
            </Graph>
            <Graph name="FILE" Title="File" type="unique">
                <Plot Title="file">
                    <cols>iget/s lookuppn/s dirblk/s</cols>
                </Plot>
            </Graph>
            <Graph name="SYSCALL" Title="Syscal" type="unique">
                <Plot Title="syscall">
                    <cols>scall/s</cols>
                </Plot>
                <Plot Title="r/w">
                    <cols>sread/s swrit/s</cols>
                </Plot>
                <Plot Title="fork">
                    <cols>fork/s exec/s</cols>
                </Plot>
                <Plot Title="char">
                    <cols>rchar/s wchar/s</cols>
                </Plot>
            </Graph>
            <Graph name="BUFFER" Title="Buffer" type="unique">
                <Plot Title="read">
                    <cols>bread/s lread/s</cols>
                </Plot>
                <Plot Title="write">
                    <cols>bwrit/s lwrit/s</cols>
                </Plot>
                <Plot Title="physical">
                    <cols>pread/s pwrit/s</cols>
                </Plot>
                <Plot Title="%">
                    <cols>%rcache %wcache</cols>
                </Plot>
            </Graph>
            <Graph name="DEVICE" Title="Device" type="multiple">
                <Plot Title="busy">
                    <cols>%busy</cols>
                </Plot>
                <Plot Title="avque">
                    <cols>avque</cols>
                </Plot>
                <Plot Title="r+w/s">
                    <cols>r+w/s</cols>
                </Plot>
                <Plot Title="blks/s">
                    <cols>blks/s</cols>
                </Plot>
                <Plot Title="Kbs/s">
                    <cols>Kbs/s</cols>
                </Plot>
                <Plot Title="avwait">
                    <cols>avwait</cols>
                </Plot>
                <Plot Title="avserv">
                    <cols>avserv</cols>
                </Plot>
            </Graph>
            <Graph name="MSGS" Title="Messages / Semaphores" type="unique">
                <Plot Title="Messages">
                    <cols>msg/s</cols>
                </Plot>
                <Plot Title="Semaphores">
                    <cols>sema/s</cols>
                </Plot>
            </Graph>
            <Graph name="SLOT" Title="Slots" type="unique">
                <Plot Title="" size="3">
                    <cols>cycle/s fault/s odio/s</cols>
                </Plot>
                <Plot Title="Slot">
                    <cols>slots</cols>
                </Plot>
            </Graph>
        </OSType>
    
    </OS>
    <!--  END OS -->
</ConfiG>

=== vlsi/ksar/src/main/resources/HPUX.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ConfiG PUBLIC "-//NET/ATOMIQUE/KSAR/CONFIG.DTD" "config.dtd">
<!--
    Description:
        Configure statistics and their corresponding graphs (plots+stacks)
-->

<ConfiG>
   
    <!--  BEGIN OS -->
    <OS>
        <OSType name="HP-UX">
            <Stat name="cpu1">
                <headerstr>%usr %sys %wio %idle</headerstr>
                <graphname>CPU</graphname>
            </Stat>
            <Stat name="device1">
                <headerstr>device %busy avque r+w/s blks/s avwait avserv</headerstr>
                <graphname>DEVICE</graphname>
            </Stat>
            <Stat name="runq">
                <headerstr>runq-sz %runocc swpq-sz %swpocc</headerstr>
                <graphname>RUNQ</graphname>
            </Stat>
            <Stat name="buffer">
                <headerstr>bread/s lread/s %rcache bwrit/s lwrit/s %wcache pread/s pwrit/s</headerstr>
                <graphname>BUFFER</graphname>
            </Stat>
            <Stat name="swap">
                <headerstr>swpin/s bswin/s swpot/s bswot/s pswch/s</headerstr>
                <graphname>SWAP</graphname>
            </Stat>
            <Stat name="syscall">
                <headerstr>scall/s sread/s swrit/s fork/s exec/s rchar/s wchar/s</headerstr>
                <graphname>SYSCALL</graphname>
            </Stat>
            <Stat name="file">
                <headerstr>iget/s namei/s dirbk/s</headerstr>
                <graphname>FILE</graphname>
            </Stat>
            <Stat name="tty">
                <headerstr>rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s</headerstr>
                <graphname>TTY</graphname>
            </Stat>
            <Stat name="ksize">
                <headerstr>text-sz ov proc-sz ov inod-sz ov file-sz ov</headerstr>
                <graphname>IGNORE</graphname>
            </Stat>
            <Stat name="msgs">
                <headerstr>msg/s sema/s</headerstr>
                <graphname>MSGS</graphname>
            </Stat>
            <Stat name="cpu2">
                <headerstr>cpu %usr %sys %wio %idle</headerstr>
                <graphname>CPU</graphname>
            </Stat>
            <Graph name="CPU" Title="CPU" type="multiple">
                <Stack Title="Used" size="3">
                    <cols>%usr %sys %wio</cols>
                    <range>0,100</range>
                </Stack>
                <Plot Title="Idle">
                    <cols>%idle</cols>
                </Plot>
            </Graph>
            <Graph name="DEVICE" Title="Device" type="multiple">
                <Plot Title="busy">
                    <cols>%busy</cols>
                </Plot>
                <Plot Title="avque">
                    <cols>avque</cols>
                </Plot>
                <Plot Title="r+w/s">
                    <cols>r+w/s</cols>
                </Plot>
                <Plot Title="blks/s">
                    <cols>blks/s</cols>
                </Plot>
                <Plot Title="avwait">
                    <cols>avwait</cols>
                </Plot>
                <Plot Title="avserv">
                    <cols>avserv</cols>
                </Plot>
            </Graph>
            <Graph name="RUNQ" Title="RunQ" type="unique">
                <Plot Title="runQ">
                    <cols>runq-sz</cols>
                </Plot>
                <Plot Title="swapQ">
                    <cols>swpq-sz</cols>
                </Plot>
            </Graph>
            <Graph name="BUFFER" Title="Buffer" type="unique">
                <Plot Title="read">
                    <cols>bread/s lread/s</cols>
                </Plot>
                <Plot Title="write">
                    <cols>bwrit/s lwrit/s</cols>
                </Plot>
                <Plot Title="physical">
                    <cols>pread/s pwrit/s</cols>
                </Plot>
                <Plot Title="%">
                    <cols>%rcache %wcache</cols>
                </Plot>
            </Graph>
            <Graph name="SWAP" Title="Swap" type="unique">
                <Plot Title="lwp">
                    <cols>swpin/s swpot/s</cols>
                </Plot>
                <Plot Title="page">
                    <cols>bswin/s bswot/s</cols>
                </Plot>
                <Plot Title="switch">
                    <cols>pswch/s</cols>
                </Plot>
            </Graph>
            <Graph name="SYSCALL" Title="Syscal" type="unique">
                <Plot Title="syscall">
                    <cols>scall/s</cols>
                </Plot>
                <Plot Title="r/w">
                    <cols>sread/s swrit/s</cols>
                </Plot>
                <Plot Title="fork">
                    <cols>fork/s exec/s</cols>
                </Plot>
                <Plot Title="char">
                    <cols>rchar/s wchar/s</cols>
                </Plot>
            </Graph>
            <Graph name="FILE" Title="File" type="unique">
                <Plot Title="file">
                    <cols>iget/s namei/s dirbk/s</cols>
                </Plot>
            </Graph>
            <Graph name="TTY" Title="Tty" type="unique">
                <Plot Title="TTY">
                    <cols>rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s</cols>
                </Plot>
            </Graph>
            <Graph name="MSGS" Title="Messages / Semaphores" type="unique">
                <Plot Title="Messages">
                    <cols>msg/s</cols>
                </Plot>
                <Plot Title="Semaphores">
                    <cols>sema/s</cols>
                </Plot>
            </Graph>
        </OSType>
    </OS>
    <!--  END OS -->
</ConfiG>
