=== vlsi/ksar/src/main/resources/Config.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Config.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE ConfiG SYSTEM "Config.dtd">

    <ConfiG>
    ...
    </ConfiG>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ConfiG (OS|colors)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT colors (itemcolor)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT itemcolor (color)*>
<!ATTLIST itemcolor
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT color (#PCDATA)>


<!ELEMENT History (cnx)*>
<!ATTLIST itemcolor
    link CDATA #IMPLIED
    type CDATA #IMPLIED
  >

<!ELEMENT cnx (command)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OS (OSType)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OSType (Graph|Stat)*>
<!ATTLIST OSType
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Stat (graphname|headerstr)*>
<!ATTLIST Stat
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT headerstr (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT graphname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Graph (Plot|Stack)*>
<!ATTLIST Graph
    type CDATA #IMPLIED
    Title CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Stack (range|cols|format)*>
<!ATTLIST Stack
    size CDATA #IMPLIED
    Title CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cols (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT range (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT format EMPTY>
<!ATTLIST format
   base CDATA #IMPLIED
   factor CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Plot (range|cols|format)*>
<!ATTLIST Plot
    size CDATA #IMPLIED
    Title CDATA #IMPLIED
  >

=== vlsi/ksar/src/main/resources/SunOS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ConfiG PUBLIC "-//NET/ATOMIQUE/KSAR/CONFIG.DTD" "config.dtd">
<!--
    Description:
        Configure statistics and their corresponding graphs (plots+stacks)
-->

<ConfiG>
   
    <!--  BEGIN OS -->
    <OS>
        <OSType name="SunOS">
            <Stat name="cpu">
                <headerstr>%usr %sys %wio %idle</headerstr>
                <graphname>CPU</graphname>
            </Stat>
            <Stat name="device">
                <headerstr>device %busy avque r+w/s blks/s avwait avserv</headerstr>
                <graphname>DEVICE</graphname>
                <duplicate>yes</duplicate>
            </Stat>
            <Stat name="runq">
                <headerstr>runq-sz %runocc swpq-sz %swpocc</headerstr>
                <graphname>IGNORE</graphname>
            </Stat>
            <Stat name="buffer">
                <headerstr>bread/s lread/s %rcache bwrit/s lwrit/s %wcache pread/s pwrit/s</headerstr>
                <graphname>BUFFER</graphname>
            </Stat>
            <Stat name="swap">
                <headerstr>swpin/s bswin/s swpot/s bswot/s pswch/s</headerstr>
                <graphname>SWAP</graphname>
            </Stat>
            <Stat name="syscall">
                <headerstr>scall/s sread/s swrit/s fork/s exec/s rchar/s wchar/s</headerstr>
                <graphname>SYSCALL</graphname>
            </Stat>
            <Stat name="file">
                <headerstr>iget/s namei/s dirbk/s</headerstr>
                <graphname>FILE</graphname>
            </Stat>
            <Stat name="tty">
                <headerstr>rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s</headerstr>
                <graphname>TTY</graphname>
            </Stat>
            <Stat name="ksize">
                <headerstr>proc-sz ov inod-sz ov file-sz ov lock-sz</headerstr>
                <graphname>IGNORE</graphname>
            </Stat>
            <Stat name="msgs">
                <headerstr>msg/s sema/s</headerstr>
                <graphname>MSGS</graphname>
            </Stat>
            <Stat name="paging1">
                <headerstr>atch/s pgin/s ppgin/s pflt/s vflt/s slock/s</headerstr>
                <graphname>PAGING1</graphname>
            </Stat>
            <Stat name="paging2">
                <headerstr>pgout/s ppgout/s pgfree/s pgscan/s %ufs_ipf</headerstr>
                <graphname>PAGING2</graphname>
            </Stat>
            <Stat name="mem">
                <headerstr>freemem freeswap</headerstr>
                <graphname>MEM</graphname>
            </Stat>
            <Stat name="kmem">
                <headerstr>sml_mem alloc fail lg_mem alloc fail ovsz_alloc fail</headerstr>
                <graphname>KMEM</graphname>
            </Stat>
            <Graph name="CPU" Title="CPU" type="unique">
                <Stack Title="Used" size="3">
                    <cols>%usr %sys %wio</cols>
                    <range>0,100</range>
                </Stack>
                <Plot Title="Idle">
                    <cols>%idle</cols>
                </Plot>
            </Graph>
            <Graph name="KMEM" Title="Kernel Memory" type="unique">
                <Plot Title="Small">
                    <cols>sml_mem</cols>
                </Plot>
                <Plot Title="Large">
                    <cols>lg_mem</cols>
                </Plot>
                <Plot Title="Oversize">
                    <cols>ovsz_alloc</cols>
                </Plot>
            </Graph>
            <Graph name="BUFFER" Title="Buffer" type="unique">
                <Plot Title="read">
                    <cols>bread/s lread/s</cols>
                </Plot>
                <Plot Title="write">
                    <cols>bwrit/s lwrit/s</cols>
                </Plot>
                <Plot Title="physical">
                    <cols>pread/s pwrit/s</cols>
                </Plot>
                <Plot Title="%">
                    <cols>%rcache %wcache</cols>
                </Plot>
            </Graph>
            <Graph name="DEVICE" Title="Device" type="multiple">
                <Plot Title="busy">
                    <cols>%busy</cols>
                </Plot>
                <Plot Title="avque">
                    <cols>avque</cols>
                </Plot>
                <Plot Title="r+w/s">
                    <cols>r+w/s</cols>
                </Plot>
                <Plot Title="blks/s">
                    <cols>blks/s</cols>
                </Plot>
                <Plot Title="avwait">
                    <cols>avwait</cols>
                </Plot>
                <Plot Title="avserv">
                    <cols>avserv</cols>
                </Plot>
            </Graph>
            <Graph name="RUNQ" Title="RunQ" type="unique">
                <Plot Title="runQ">
                    <cols>runq-sz</cols>
                </Plot>
                <Plot Title="swapQ">
                    <cols>swpq-sz</cols>
                </Plot>
            </Graph>
            <Graph name="SWAP" Title="Swap" type="unique">
                <Plot Title="lwp">
                    <cols>swpin/s swpot/s</cols>
                </Plot>
                <Plot Title="page">
                    <cols>bswin/s bswot/s</cols>
                </Plot>
                <Plot Title="switch">
                    <cols>pswch/s</cols>
                </Plot>
            </Graph>
            <Graph name="SYSCALL" Title="Syscal" type="unique">
                <Plot Title="syscall">
                    <cols>scall/s</cols>
                </Plot>
                <Plot Title="r/w">
                    <cols>sread/s swrit/s</cols>
                </Plot>
                <Plot Title="fork">
                    <cols>fork/s exec/s</cols>
                </Plot>
                <Plot Title="char">
                    <cols>rchar/s wchar/s</cols>
                </Plot>
            </Graph>
            <Graph name="FILE" Title="File" type="unique">
                <Plot Title="file">
                    <cols>iget/s namei/s dirbk/s</cols>
                </Plot>
            </Graph>
            <Graph name="TTY" Title="Tty" type="unique">
                <Plot Title="TTY">
                    <cols>rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s</cols>
                </Plot>
            </Graph>
            <Graph name="MSGS" Title="Messages / Semaphores" type="unique">
                <Plot Title="Messages">
                    <cols>msg/s</cols>
                </Plot>
                <Plot Title="Semaphores">
                    <cols>sema/s</cols>
                </Plot>
            </Graph>
            <Graph name="PAGING1" Title="Paging1" type="unique">
                <Plot Title="atch">
                    <cols>atch/s</cols>
                </Plot>
                <Plot Title="in">
                    <cols>pgin/s ppgin/s</cols>
                </Plot>
                <Plot Title="fault">
                    <cols>pflt/s vflt/s</cols>
                </Plot>
                <Plot Title="lock">
                    <cols>slock/s</cols>
                </Plot>
            </Graph>
            <Graph name="PAGING2" Title="Paging2" type="unique">
                <Plot Title="out">
                    <cols>pgout/s ppgout/s</cols>
                </Plot>
                <Plot Title="free">
                    <cols>pgfree/s</cols>
                </Plot>
                <Plot Title="scan">
                    <cols>pgscan/s</cols>
                </Plot>
                <Plot Title="ufs_ipf">
                    <cols>%ufs_ipf</cols>
                </Plot>
            </Graph>
            <Graph name="MEM" Title="Memory" type="unique">
                <Plot Title="freemem">
                    <cols>freemem</cols>
                </Plot>
                <Plot Title="freeswap">
                    <cols>freeswap</cols>
                </Plot>
            </Graph>
        </OSType>

    </OS>
    <!--  END OS -->
</ConfiG>
